openapi: 3.0.2
info:
  title: FDK information model harvester
  description: Tilgjengeliggjør informasjonsmodeller fra en katalog ihht DCAT-AP-NO
  version: '1.0'
  contact:
    name: Digitaliseringsdirektoratet
    url: 'https://fellesdatakatalog.digdir.no'
    email: fellesdatakatalog@digdir.no
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
tags:
  - name: dcat-ap-no-catalogs
    description: DCAT-AP-NO catalogs
  - name: dcat-ap-no-informationmodels
    description: DCAT-AP-NO informationmodels
servers:
  - url: 'https://informationmodels.fellesdatakatalog.digdir.no'
    description: Produksjonsmiljø
  - url: 'https://informationmodels.staging.fellesdatakatalog.digdir.no'
    description: Testmiljø
  - url: 'https://informationmodels.demo.fellesdatakatalog.digdir.no'
    description: Demomiljø
paths:
  /catalogs:
    get:
      tags:
        - dcat-ap-no-catalogs
      description: Returns a collection of catalogs
      operationId: getCatalogs
      responses:
        '200':
          description: OK
          content:
            text/turtle:
              schema:
                type: string
            text/n3:
              schema:
                type: string
            application/rdf+json:
              schema:
                type: string
            application/ld+json:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
            application/n-triples:
              schema:
                type: string
  '/catalogs/{id}':
    get:
      tags:
        - dcat-ap-no-catalogs
      description: Returns a catalog
      operationId: getCatalogById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            text/turtle:
              schema:
                type: string
            text/n3:
              schema:
                type: string
            application/rdf+json:
              schema:
                type: string
            application/ld+json:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
            application/n-triples:
              schema:
                type: string
        '404':
          description: Dataset catalog with requested id does not exist
  '/informationmodels/{id}':
    get:
      tags:
        - dcat-ap-no-informationmodels
      description: Returnerer en informasjonsmodell
      operationId: getInformationModelById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            text/turtle:
              schema:
                type: string
            text/n3:
              schema:
                type: string
            application/rdf+json:
              schema:
                type: string
            application/ld+json:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
            application/n-triples:
              schema:
                type: string
        '404':
          description: Information model with requested id does not exist
