spring:
  jackson:
    default-property-inclusion: non_null
  data:
    elasticsearch:
      clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
      clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    template:
      routing-key: 'harvester.UpdateSearchTrigger'
      exchange: 'updates'
logging:
  level.root: WARN
  level.no.fdk.imcat: DEBUG
  level.no.fdk.imcat.service: DEBUG
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.springframework.data.elasticsearch: ${LOG_LEVEL:INFO}
application:
  apiRootUrl: http://fdk-nginx-search:8080/api
  referenceDataUrl: ${FDK_REFERENCE_DATA_URL}
  organizationCatalogueUrl: ${FDK_ORGANIZATION_CATALOGUE_URL}
  harvestSourceUri: https://fellesdatakatalog.brreg.no/api
  harvestSourceURIBase: ${FDK_ALTINN_MODELS_URL:https://fdk-dev-altinn.appspot.com/api/v1/schemas}
  harvestAdminRootUrl: ${HARVEST_ADMIN_ROOT_URL:http://localhost:8135/api}
  # harvest every sixth hour, 10 minutes after apicatalogs update
  harvestCron: 0 10 */6 * * *



---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop, unit-integration
  data:
    elasticsearch:
      clusterNodes: localhost:9300
      clusterName: elasticsearch
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
application:
  apiRootUrl: http://localhost:8080/api
  referenceDataUrl: ${FDK_REFERENCE_DATA_URL:https://fellesdatakatalog.brreg.no/reference-data}
  organizationCatalogueUrl: ${FDK_ORGANIZATION_CATALOGUE_URL:https://organization-catalogue.fellesdatakatalog.brreg.no}
server:
  port: 8109

---
#Test-miljø
spring:
  profiles: test
  data:
    elasticsearch:
      clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
      clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}
application:
  apiRootUrl: ${WIREMOCK_TEST_HOST}/api
  harvestSourceUri: ${WIREMOCK_TEST_HOST}/api
  harvestSourceURIBase: ${WIREMOCK_TEST_HOST}/api/v1/schemas
server:
  port: 8080
