logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
  level.org.apache.jena: ERROR
server:
  port: 8080
fuseki:
  unionGraphUri: ${FDK_SPARQL_SERVICE_URI:http://fdk-sparql-service:8080}/fuseki/harvested?graph=https://informationmodels.fellesdatakatalog.digdir.no
application:
  informationModelUri: ${FDK_INFORMATIONMODEL_HARVESTER_URI:https://informationmodels.staging.fellesdatakatalog.digdir.no}/informationmodels
  catalogUri: ${FDK_INFORMATIONMODEL_HARVESTER_URI:https://informationmodels.staging.fellesdatakatalog.digdir.no}/catalogs
  harvestAdminRootUrl: ${HARVEST_ADMIN_ROOT_URL:http://fdk-harvest-admin:8080/api}
spring:
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: ${SSO_HOST:https://sso.staging.fellesdatakatalog.digdir.no}/auth/realms/fdk/protocol/openid-connect/certs
    issuer-uri: ${SSO_HOST:https://sso.staging.fellesdatakatalog.digdir.no}/auth/realms/fdk
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  data.mongodb.uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/informationModelHarvester?authSource=admin&authMechanism=SCRAM-SHA-1
management:
  endpoints:
    web:
      exposure:
        include: health, info
  metrics:
    export:
      statsd:
        enabled: true
        flavor: telegraf
        host: fdk-monitoring-services-telegraf
        port: 8125
    tags:
      application: fdk-informationmodel-harvester
---
spring:
  config.activate.on-profile: develop
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  data.mongodb.uri: mongodb://admin:admin@localhost:27017/informationModelHarvester?authSource=admin&authMechanism=SCRAM-SHA-1
fuseki:
  unionGraphUri: http://localhost:3030/fuseki/harvested?graph=https://informationmodels.fellesdatakatalog.digdir.no
application:
  informationModelUri: https://informationmodels.staging.fellesdatakatalog.digdir.no/informationmodels
  catalogUri: https://informationmodels.staging.fellesdatakatalog.digdir.no/catalogs
  harvestAdminRootUrl: https://admin-api.staging.fellesdatakatalog.digdir.no/api

---
spring:
  config.activate.on-profile: contract-test
  security.oauth2.resourceserver.jwt:
    jwk-set-uri: http://localhost:5000/auth/realms/fdk/protocol/openid-connect/certs
    issuer-uri: http://localhost:5000/auth/realms/fdk
  rabbitmq:
    host: localhost
    port: 5001
    username: admin
    password: admin
application:
  informationModelUri: http://localhost:5000/informationmodels
  catalogUri: http://localhost:5000/catalogs
  harvestAdminRootUrl: http://localhost:5000/api
fuseki.unionGraphUri: http://localhost:5000/fuseki/harvested?graph=https://informationmodels.fellesdatakatalog.digdir.no
