---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fdk-informationmodel-harvester
  name: fdk-informationmodel-harvester
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: fdk-informationmodel-harvester
