---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fdk-informationmodel-harvester-deployment.yaml
  - fdk-informationmodel-harvester-service.yaml
images:
  - name: fdk-informationmodel-harvester
    newName: ghcr.io/informasjonsforvaltning/fdk-informationmodel-harvester
    newTag: $(GIT_COMMIT_SHA)
