name: Run tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Package with maven
        run: mvn clean package --no-transfer-progress

      - name: Build Docker image
        run: docker build -f Dockerfile.prod . -t eu.gcr.io/fdk-infra/fdk-informationmodel-harvester:latest

      - name: Set max map count for elasticsearch
        run: sudo sysctl -w vm.max_map_count=262144

      - name: Run tests
        run: mvn verify --no-transfer-progress
